services:
  app:
    image: ghcr.io/pale66/transcription_bot:main
    volumes:
      - bot_data:/app/data/
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN:?BOT_TOKEN is required}
      - COMPLETION_URL=${COMPLETION_URL:?COMPLETION_URL is required}
      - WHISPER_URL=${WHISPER_URL:?YOUR_WHISPER_URL is required}
      - PROXY_URL=${PROXY_URL}
volumes:
  bot_data:
